// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// 이 파일은 수동 생성되었으며 DeepCopy 메서드를 제공합니다.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the same type
func (in *StorageHPA) DeepCopyInto(out *StorageHPA) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of StorageHPA
func (in *StorageHPA) DeepCopy() *StorageHPA {
	if in == nil {
		return nil
	}
	out := new(StorageHPA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject creates a deep copy as runtime.Object
func (in *StorageHPA) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of StorageHPAList
func (in *StorageHPAList) DeepCopyInto(out *StorageHPAList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageHPA, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of StorageHPAList
func (in *StorageHPAList) DeepCopy() *StorageHPAList {
	if in == nil {
		return nil
	}
	out := new(StorageHPAList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject creates a deep copy as runtime.Object
func (in *StorageHPAList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of StorageHPASpec
func (in *StorageHPASpec) DeepCopyInto(out *StorageHPASpec) {
	*out = *in
	out.WorkloadRef = in.WorkloadRef
	if in.TargetCPUPercent != nil {
		in, out := &in.TargetCPUPercent, &out.TargetCPUPercent
		*out = new(int32)
		**out = **in
	}
	if in.TargetMemoryPercent != nil {
		in, out := &in.TargetMemoryPercent, &out.TargetMemoryPercent
		*out = new(int32)
		**out = **in
	}
	if in.TargetGPUPercent != nil {
		in, out := &in.TargetGPUPercent, &out.TargetGPUPercent
		*out = new(int32)
		**out = **in
	}
	if in.TargetStorageReadThroughput != nil {
		in, out := &in.TargetStorageReadThroughput, &out.TargetStorageReadThroughput
		*out = new(int64)
		**out = **in
	}
	if in.TargetStorageWriteThroughput != nil {
		in, out := &in.TargetStorageWriteThroughput, &out.TargetStorageWriteThroughput
		*out = new(int64)
		**out = **in
	}
	if in.TargetStorageIOPS != nil {
		in, out := &in.TargetStorageIOPS, &out.TargetStorageIOPS
		*out = new(int64)
		**out = **in
	}
	if in.ScaleUpPolicy != nil {
		in, out := &in.ScaleUpPolicy, &out.ScaleUpPolicy
		*out = new(ScalingPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ScaleDownPolicy != nil {
		in, out := &in.ScaleDownPolicy, &out.ScaleDownPolicy
		*out = new(ScalingPolicySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy creates a deep copy of StorageHPASpec
func (in *StorageHPASpec) DeepCopy() *StorageHPASpec {
	if in == nil {
		return nil
	}
	out := new(StorageHPASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of StorageHPAStatus
func (in *StorageHPAStatus) DeepCopyInto(out *StorageHPAStatus) {
	*out = *in
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of StorageHPAStatus
func (in *StorageHPAStatus) DeepCopy() *StorageHPAStatus {
	if in == nil {
		return nil
	}
	out := new(StorageHPAStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of ScalingPolicySpec
func (in *ScalingPolicySpec) DeepCopyInto(out *ScalingPolicySpec) {
	*out = *in
	if in.StabilizationWindowSeconds != nil {
		in, out := &in.StabilizationWindowSeconds, &out.StabilizationWindowSeconds
		*out = new(int32)
		**out = **in
	}
	if in.MaxScaleChange != nil {
		in, out := &in.MaxScaleChange, &out.MaxScaleChange
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy creates a deep copy of ScalingPolicySpec
func (in *ScalingPolicySpec) DeepCopy() *ScalingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ScalingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of WorkloadReference
func (in *WorkloadReference) DeepCopyInto(out *WorkloadReference) {
	*out = *in
}

// DeepCopy creates a deep copy of WorkloadReference
func (in *WorkloadReference) DeepCopy() *WorkloadReference {
	if in == nil {
		return nil
	}
	out := new(WorkloadReference)
	in.DeepCopyInto(out)
	return out
}
