apiVersion: v1
kind: Pod
metadata:
  name: hubble-traffic-generator
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/hostname: ai-storage-master
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: curl
    image: curlimages/curl
    command: ["/bin/sh", "-c", "while true; do curl -s https://www.google.com > /dev/null; curl -s https://www.kubernetes.io > /dev/null; sleep 0.5; done"]
