# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hub.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hub.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\thub.proto\x12\x0einsight.hub.v1\"\x9b\x01\n\x10ResourceSnapshot\x12\x19\n\x11timestamp_unix_ms\x18\x01 \x01(\x03\x12\x17\n\x0f\x63pu_utilization\x18\x02 \x01(\x01\x12\x1a\n\x12memory_utilization\x18\x03 \x01(\x01\x12\x17\n\x0fgpu_utilization\x18\x04 \x01(\x01\x12\x1e\n\x16storage_io_utilization\x18\x05 \x01(\x01\"^\n\x14SubmitHistoryRequest\x12\x11\n\tnode_name\x18\x01 \x01(\t\x12\x33\n\tsnapshots\x18\x02 \x03(\x0b\x32 .insight.hub.v1.ResourceSnapshot\"F\n\x15SubmitHistoryResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x1b\n\x13snapshots_processed\x18\x02 \x01(\x05\"X\n\x15GetNodeHistoryRequest\x12\x11\n\tnode_name\x18\x01 \x01(\t\x12\x15\n\rsince_unix_ms\x18\x02 \x01(\x03\x12\x15\n\rmax_snapshots\x18\x03 \x01(\x05\"M\n\x16GetNodeHistoryResponse\x12\x33\n\tsnapshots\x18\x01 \x03(\x0b\x32 .insight.hub.v1.ResourceSnapshot\"\x12\n\x10ListNodesRequest\"\'\n\x11ListNodesResponse\x12\x12\n\nnode_names\x18\x01 \x03(\t\"\x14\n\x12HealthCheckRequest\"P\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x17\n\x0ftotal_snapshots\x18\x03 \x01(\x03\x32\x80\x03\n\x11InsightHubService\x12`\n\x11SubmitHistoryData\x12$.insight.hub.v1.SubmitHistoryRequest\x1a%.insight.hub.v1.SubmitHistoryResponse\x12_\n\x0eGetNodeHistory\x12%.insight.hub.v1.GetNodeHistoryRequest\x1a&.insight.hub.v1.GetNodeHistoryResponse\x12P\n\tListNodes\x12 .insight.hub.v1.ListNodesRequest\x1a!.insight.hub.v1.ListNodesResponse\x12V\n\x0bHealthCheck\x12\".insight.hub.v1.HealthCheckRequest\x1a#.insight.hub.v1.HealthCheckResponseB\x19Z\x17insight-hub/proto/hubpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\027insight-hub/proto/hubpb'
  _globals['_RESOURCESNAPSHOT']._serialized_start=30
  _globals['_RESOURCESNAPSHOT']._serialized_end=185
  _globals['_SUBMITHISTORYREQUEST']._serialized_start=187
  _globals['_SUBMITHISTORYREQUEST']._serialized_end=281
  _globals['_SUBMITHISTORYRESPONSE']._serialized_start=283
  _globals['_SUBMITHISTORYRESPONSE']._serialized_end=353
  _globals['_GETNODEHISTORYREQUEST']._serialized_start=355
  _globals['_GETNODEHISTORYREQUEST']._serialized_end=443
  _globals['_GETNODEHISTORYRESPONSE']._serialized_start=445
  _globals['_GETNODEHISTORYRESPONSE']._serialized_end=522
  _globals['_LISTNODESREQUEST']._serialized_start=524
  _globals['_LISTNODESREQUEST']._serialized_end=542
  _globals['_LISTNODESRESPONSE']._serialized_start=544
  _globals['_LISTNODESRESPONSE']._serialized_end=583
  _globals['_HEALTHCHECKREQUEST']._serialized_start=585
  _globals['_HEALTHCHECKREQUEST']._serialized_end=605
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=607
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=687
  _globals['_INSIGHTHUBSERVICE']._serialized_start=690
  _globals['_INSIGHTHUBSERVICE']._serialized_end=1074
# @@protoc_insertion_point(module_scope)
