# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hub_pb2 as hub__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hub_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InsightHubServiceStub(object):
    """Insight Hub: persistent store for node resource history from insight-scope.
    Forecaster pulls via GetNodeHistory / ListNodes instead of receiving SubmitHistoryData directly.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitHistoryData = channel.unary_unary(
                '/insight.hub.v1.InsightHubService/SubmitHistoryData',
                request_serializer=hub__pb2.SubmitHistoryRequest.SerializeToString,
                response_deserializer=hub__pb2.SubmitHistoryResponse.FromString,
                _registered_method=True)
        self.GetNodeHistory = channel.unary_unary(
                '/insight.hub.v1.InsightHubService/GetNodeHistory',
                request_serializer=hub__pb2.GetNodeHistoryRequest.SerializeToString,
                response_deserializer=hub__pb2.GetNodeHistoryResponse.FromString,
                _registered_method=True)
        self.ListNodes = channel.unary_unary(
                '/insight.hub.v1.InsightHubService/ListNodes',
                request_serializer=hub__pb2.ListNodesRequest.SerializeToString,
                response_deserializer=hub__pb2.ListNodesResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/insight.hub.v1.InsightHubService/HealthCheck',
                request_serializer=hub__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=hub__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class InsightHubServiceServicer(object):
    """Insight Hub: persistent store for node resource history from insight-scope.
    Forecaster pulls via GetNodeHistory / ListNodes instead of receiving SubmitHistoryData directly.
    """

    def SubmitHistoryData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InsightHubServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitHistoryData': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitHistoryData,
                    request_deserializer=hub__pb2.SubmitHistoryRequest.FromString,
                    response_serializer=hub__pb2.SubmitHistoryResponse.SerializeToString,
            ),
            'GetNodeHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeHistory,
                    request_deserializer=hub__pb2.GetNodeHistoryRequest.FromString,
                    response_serializer=hub__pb2.GetNodeHistoryResponse.SerializeToString,
            ),
            'ListNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodes,
                    request_deserializer=hub__pb2.ListNodesRequest.FromString,
                    response_serializer=hub__pb2.ListNodesResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=hub__pb2.HealthCheckRequest.FromString,
                    response_serializer=hub__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'insight.hub.v1.InsightHubService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('insight.hub.v1.InsightHubService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InsightHubService(object):
    """Insight Hub: persistent store for node resource history from insight-scope.
    Forecaster pulls via GetNodeHistory / ListNodes instead of receiving SubmitHistoryData directly.
    """

    @staticmethod
    def SubmitHistoryData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/insight.hub.v1.InsightHubService/SubmitHistoryData',
            hub__pb2.SubmitHistoryRequest.SerializeToString,
            hub__pb2.SubmitHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/insight.hub.v1.InsightHubService/GetNodeHistory',
            hub__pb2.GetNodeHistoryRequest.SerializeToString,
            hub__pb2.GetNodeHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/insight.hub.v1.InsightHubService/ListNodes',
            hub__pb2.ListNodesRequest.SerializeToString,
            hub__pb2.ListNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/insight.hub.v1.InsightHubService/HealthCheck',
            hub__pb2.HealthCheckRequest.SerializeToString,
            hub__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
