apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-storage-workloads
resources:
  - 00-shared.yaml
  - 10-preprocess-job.yaml
  - 20-train-job.yaml
  - 30-inference-job.yaml
images:
  - name: cifar10
    newName: ketidevit2/cifar10
    newTag: "latest"   # CI (image.yml) bumps this to the 7-char commit SHA on build
