// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: apollo.proto

package apollo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchedulingPolicyService_GetSchedulingPolicy_FullMethodName    = "/apollo.SchedulingPolicyService/GetSchedulingPolicy"
	SchedulingPolicyService_ReportSchedulingResult_FullMethodName = "/apollo.SchedulingPolicyService/ReportSchedulingResult"
)

// SchedulingPolicyServiceClient is the client API for SchedulingPolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchedulingPolicyServiceClient interface {
	GetSchedulingPolicy(ctx context.Context, in *SchedulingPolicyRequest, opts ...grpc.CallOption) (*SchedulingPolicy, error)
	ReportSchedulingResult(ctx context.Context, in *SchedulingResult, opts ...grpc.CallOption) (*ReportResponse, error)
}

type schedulingPolicyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulingPolicyServiceClient(cc grpc.ClientConnInterface) SchedulingPolicyServiceClient {
	return &schedulingPolicyServiceClient{cc}
}

func (c *schedulingPolicyServiceClient) GetSchedulingPolicy(ctx context.Context, in *SchedulingPolicyRequest, opts ...grpc.CallOption) (*SchedulingPolicy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchedulingPolicy)
	err := c.cc.Invoke(ctx, SchedulingPolicyService_GetSchedulingPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingPolicyServiceClient) ReportSchedulingResult(ctx context.Context, in *SchedulingResult, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, SchedulingPolicyService_ReportSchedulingResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulingPolicyServiceServer is the server API for SchedulingPolicyService service.
// All implementations must embed UnimplementedSchedulingPolicyServiceServer
// for forward compatibility.
type SchedulingPolicyServiceServer interface {
	GetSchedulingPolicy(context.Context, *SchedulingPolicyRequest) (*SchedulingPolicy, error)
	ReportSchedulingResult(context.Context, *SchedulingResult) (*ReportResponse, error)
	mustEmbedUnimplementedSchedulingPolicyServiceServer()
}

// UnimplementedSchedulingPolicyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulingPolicyServiceServer struct{}

func (UnimplementedSchedulingPolicyServiceServer) GetSchedulingPolicy(context.Context, *SchedulingPolicyRequest) (*SchedulingPolicy, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchedulingPolicy not implemented")
}
func (UnimplementedSchedulingPolicyServiceServer) ReportSchedulingResult(context.Context, *SchedulingResult) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportSchedulingResult not implemented")
}
func (UnimplementedSchedulingPolicyServiceServer) mustEmbedUnimplementedSchedulingPolicyServiceServer() {
}
func (UnimplementedSchedulingPolicyServiceServer) testEmbeddedByValue() {}

// UnsafeSchedulingPolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulingPolicyServiceServer will
// result in compilation errors.
type UnsafeSchedulingPolicyServiceServer interface {
	mustEmbedUnimplementedSchedulingPolicyServiceServer()
}

func RegisterSchedulingPolicyServiceServer(s grpc.ServiceRegistrar, srv SchedulingPolicyServiceServer) {
	// If the following call panics, it indicates UnimplementedSchedulingPolicyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchedulingPolicyService_ServiceDesc, srv)
}

func _SchedulingPolicyService_GetSchedulingPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulingPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingPolicyServiceServer).GetSchedulingPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingPolicyService_GetSchedulingPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingPolicyServiceServer).GetSchedulingPolicy(ctx, req.(*SchedulingPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingPolicyService_ReportSchedulingResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchedulingResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingPolicyServiceServer).ReportSchedulingResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingPolicyService_ReportSchedulingResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingPolicyServiceServer).ReportSchedulingResult(ctx, req.(*SchedulingResult))
	}
	return interceptor(ctx, in, info, handler)
}

// SchedulingPolicyService_ServiceDesc is the grpc.ServiceDesc for SchedulingPolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchedulingPolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apollo.SchedulingPolicyService",
	HandlerType: (*SchedulingPolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSchedulingPolicy",
			Handler:    _SchedulingPolicyService_GetSchedulingPolicy_Handler,
		},
		{
			MethodName: "ReportSchedulingResult",
			Handler:    _SchedulingPolicyService_ReportSchedulingResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apollo.proto",
}
