// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: apollo.proto

package apollo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SchedulingDecision int32

const (
	SchedulingDecision_SCHEDULING_DECISION_UNSPECIFIED SchedulingDecision = 0
	SchedulingDecision_SCHEDULING_DECISION_ALLOW       SchedulingDecision = 1
	SchedulingDecision_SCHEDULING_DECISION_PREFER      SchedulingDecision = 2
	SchedulingDecision_SCHEDULING_DECISION_REQUIRE     SchedulingDecision = 3
	SchedulingDecision_SCHEDULING_DECISION_DELAY       SchedulingDecision = 4
	SchedulingDecision_SCHEDULING_DECISION_REJECT      SchedulingDecision = 5
)

// Enum value maps for SchedulingDecision.
var (
	SchedulingDecision_name = map[int32]string{
		0: "SCHEDULING_DECISION_UNSPECIFIED",
		1: "SCHEDULING_DECISION_ALLOW",
		2: "SCHEDULING_DECISION_PREFER",
		3: "SCHEDULING_DECISION_REQUIRE",
		4: "SCHEDULING_DECISION_DELAY",
		5: "SCHEDULING_DECISION_REJECT",
	}
	SchedulingDecision_value = map[string]int32{
		"SCHEDULING_DECISION_UNSPECIFIED": 0,
		"SCHEDULING_DECISION_ALLOW":       1,
		"SCHEDULING_DECISION_PREFER":      2,
		"SCHEDULING_DECISION_REQUIRE":     3,
		"SCHEDULING_DECISION_DELAY":       4,
		"SCHEDULING_DECISION_REJECT":      5,
	}
)

func (x SchedulingDecision) Enum() *SchedulingDecision {
	p := new(SchedulingDecision)
	*p = x
	return p
}

func (x SchedulingDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchedulingDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_apollo_proto_enumTypes[0].Descriptor()
}

func (SchedulingDecision) Type() protoreflect.EnumType {
	return &file_apollo_proto_enumTypes[0]
}

func (x SchedulingDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchedulingDecision.Descriptor instead.
func (SchedulingDecision) EnumDescriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{0}
}

type WorkloadType int32

const (
	WorkloadType_WORKLOAD_TYPE_UNKNOWN    WorkloadType = 0
	WorkloadType_WORKLOAD_TYPE_IMAGE      WorkloadType = 1
	WorkloadType_WORKLOAD_TYPE_TEXT       WorkloadType = 2
	WorkloadType_WORKLOAD_TYPE_TABULAR    WorkloadType = 3
	WorkloadType_WORKLOAD_TYPE_AUDIO      WorkloadType = 4
	WorkloadType_WORKLOAD_TYPE_VIDEO      WorkloadType = 5
	WorkloadType_WORKLOAD_TYPE_MULTIMODAL WorkloadType = 6
	WorkloadType_WORKLOAD_TYPE_GENERIC    WorkloadType = 7
)

// Enum value maps for WorkloadType.
var (
	WorkloadType_name = map[int32]string{
		0: "WORKLOAD_TYPE_UNKNOWN",
		1: "WORKLOAD_TYPE_IMAGE",
		2: "WORKLOAD_TYPE_TEXT",
		3: "WORKLOAD_TYPE_TABULAR",
		4: "WORKLOAD_TYPE_AUDIO",
		5: "WORKLOAD_TYPE_VIDEO",
		6: "WORKLOAD_TYPE_MULTIMODAL",
		7: "WORKLOAD_TYPE_GENERIC",
	}
	WorkloadType_value = map[string]int32{
		"WORKLOAD_TYPE_UNKNOWN":    0,
		"WORKLOAD_TYPE_IMAGE":      1,
		"WORKLOAD_TYPE_TEXT":       2,
		"WORKLOAD_TYPE_TABULAR":    3,
		"WORKLOAD_TYPE_AUDIO":      4,
		"WORKLOAD_TYPE_VIDEO":      5,
		"WORKLOAD_TYPE_MULTIMODAL": 6,
		"WORKLOAD_TYPE_GENERIC":    7,
	}
)

func (x WorkloadType) Enum() *WorkloadType {
	p := new(WorkloadType)
	*p = x
	return p
}

func (x WorkloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_apollo_proto_enumTypes[1].Descriptor()
}

func (WorkloadType) Type() protoreflect.EnumType {
	return &file_apollo_proto_enumTypes[1]
}

func (x WorkloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadType.Descriptor instead.
func (WorkloadType) EnumDescriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{1}
}

type PipelineStage int32

const (
	PipelineStage_PIPELINE_STAGE_UNKNOWN        PipelineStage = 0
	PipelineStage_PIPELINE_STAGE_DATA_LOADING   PipelineStage = 1
	PipelineStage_PIPELINE_STAGE_PREPROCESSING  PipelineStage = 2
	PipelineStage_PIPELINE_STAGE_TRAINING       PipelineStage = 3
	PipelineStage_PIPELINE_STAGE_VALIDATION     PipelineStage = 4
	PipelineStage_PIPELINE_STAGE_INFERENCE      PipelineStage = 5
	PipelineStage_PIPELINE_STAGE_POSTPROCESSING PipelineStage = 6
	PipelineStage_PIPELINE_STAGE_CHECKPOINTING  PipelineStage = 7
	PipelineStage_PIPELINE_STAGE_IDLE           PipelineStage = 8
)

// Enum value maps for PipelineStage.
var (
	PipelineStage_name = map[int32]string{
		0: "PIPELINE_STAGE_UNKNOWN",
		1: "PIPELINE_STAGE_DATA_LOADING",
		2: "PIPELINE_STAGE_PREPROCESSING",
		3: "PIPELINE_STAGE_TRAINING",
		4: "PIPELINE_STAGE_VALIDATION",
		5: "PIPELINE_STAGE_INFERENCE",
		6: "PIPELINE_STAGE_POSTPROCESSING",
		7: "PIPELINE_STAGE_CHECKPOINTING",
		8: "PIPELINE_STAGE_IDLE",
	}
	PipelineStage_value = map[string]int32{
		"PIPELINE_STAGE_UNKNOWN":        0,
		"PIPELINE_STAGE_DATA_LOADING":   1,
		"PIPELINE_STAGE_PREPROCESSING":  2,
		"PIPELINE_STAGE_TRAINING":       3,
		"PIPELINE_STAGE_VALIDATION":     4,
		"PIPELINE_STAGE_INFERENCE":      5,
		"PIPELINE_STAGE_POSTPROCESSING": 6,
		"PIPELINE_STAGE_CHECKPOINTING":  7,
		"PIPELINE_STAGE_IDLE":           8,
	}
)

func (x PipelineStage) Enum() *PipelineStage {
	p := new(PipelineStage)
	*p = x
	return p
}

func (x PipelineStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PipelineStage) Descriptor() protoreflect.EnumDescriptor {
	return file_apollo_proto_enumTypes[2].Descriptor()
}

func (PipelineStage) Type() protoreflect.EnumType {
	return &file_apollo_proto_enumTypes[2]
}

func (x PipelineStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PipelineStage.Descriptor instead.
func (PipelineStage) EnumDescriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{2}
}

type IOPattern int32

const (
	IOPattern_IO_PATTERN_UNKNOWN     IOPattern = 0
	IOPattern_IO_PATTERN_READ_HEAVY  IOPattern = 1
	IOPattern_IO_PATTERN_WRITE_HEAVY IOPattern = 2
	IOPattern_IO_PATTERN_BALANCED    IOPattern = 3
	IOPattern_IO_PATTERN_SEQUENTIAL  IOPattern = 4
	IOPattern_IO_PATTERN_RANDOM      IOPattern = 5
	IOPattern_IO_PATTERN_BURSTY      IOPattern = 6
)

// Enum value maps for IOPattern.
var (
	IOPattern_name = map[int32]string{
		0: "IO_PATTERN_UNKNOWN",
		1: "IO_PATTERN_READ_HEAVY",
		2: "IO_PATTERN_WRITE_HEAVY",
		3: "IO_PATTERN_BALANCED",
		4: "IO_PATTERN_SEQUENTIAL",
		5: "IO_PATTERN_RANDOM",
		6: "IO_PATTERN_BURSTY",
	}
	IOPattern_value = map[string]int32{
		"IO_PATTERN_UNKNOWN":     0,
		"IO_PATTERN_READ_HEAVY":  1,
		"IO_PATTERN_WRITE_HEAVY": 2,
		"IO_PATTERN_BALANCED":    3,
		"IO_PATTERN_SEQUENTIAL":  4,
		"IO_PATTERN_RANDOM":      5,
		"IO_PATTERN_BURSTY":      6,
	}
)

func (x IOPattern) Enum() *IOPattern {
	p := new(IOPattern)
	*p = x
	return p
}

func (x IOPattern) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IOPattern) Descriptor() protoreflect.EnumDescriptor {
	return file_apollo_proto_enumTypes[3].Descriptor()
}

func (IOPattern) Type() protoreflect.EnumType {
	return &file_apollo_proto_enumTypes[3]
}

func (x IOPattern) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IOPattern.Descriptor instead.
func (IOPattern) EnumDescriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{3}
}

type StorageClass int32

const (
	StorageClass_STORAGE_CLASS_UNSPECIFIED StorageClass = 0
	StorageClass_STORAGE_CLASS_STANDARD    StorageClass = 1
	StorageClass_STORAGE_CLASS_FAST        StorageClass = 2
	StorageClass_STORAGE_CLASS_ULTRA_FAST  StorageClass = 3
	StorageClass_STORAGE_CLASS_CSD         StorageClass = 4
	StorageClass_STORAGE_CLASS_MEMORY      StorageClass = 5
)

// Enum value maps for StorageClass.
var (
	StorageClass_name = map[int32]string{
		0: "STORAGE_CLASS_UNSPECIFIED",
		1: "STORAGE_CLASS_STANDARD",
		2: "STORAGE_CLASS_FAST",
		3: "STORAGE_CLASS_ULTRA_FAST",
		4: "STORAGE_CLASS_CSD",
		5: "STORAGE_CLASS_MEMORY",
	}
	StorageClass_value = map[string]int32{
		"STORAGE_CLASS_UNSPECIFIED": 0,
		"STORAGE_CLASS_STANDARD":    1,
		"STORAGE_CLASS_FAST":        2,
		"STORAGE_CLASS_ULTRA_FAST":  3,
		"STORAGE_CLASS_CSD":         4,
		"STORAGE_CLASS_MEMORY":      5,
	}
)

func (x StorageClass) Enum() *StorageClass {
	p := new(StorageClass)
	*p = x
	return p
}

func (x StorageClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageClass) Descriptor() protoreflect.EnumDescriptor {
	return file_apollo_proto_enumTypes[4].Descriptor()
}

func (StorageClass) Type() protoreflect.EnumType {
	return &file_apollo_proto_enumTypes[4]
}

func (x StorageClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageClass.Descriptor instead.
func (StorageClass) EnumDescriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{4}
}

type PreprocessingType int32

const (
	PreprocessingType_PREPROCESSING_TYPE_UNKNOWN         PreprocessingType = 0
	PreprocessingType_PREPROCESSING_TYPE_AUGMENTATION    PreprocessingType = 1
	PreprocessingType_PREPROCESSING_TYPE_TRANSFORMATION  PreprocessingType = 2
	PreprocessingType_PREPROCESSING_TYPE_FILTERING       PreprocessingType = 3
	PreprocessingType_PREPROCESSING_TYPE_AGGREGATION     PreprocessingType = 4
	PreprocessingType_PREPROCESSING_TYPE_SHARDING        PreprocessingType = 5
	PreprocessingType_PREPROCESSING_TYPE_NORMALIZATION   PreprocessingType = 6
	PreprocessingType_PREPROCESSING_TYPE_FEATURE_EXTRACT PreprocessingType = 7
)

// Enum value maps for PreprocessingType.
var (
	PreprocessingType_name = map[int32]string{
		0: "PREPROCESSING_TYPE_UNKNOWN",
		1: "PREPROCESSING_TYPE_AUGMENTATION",
		2: "PREPROCESSING_TYPE_TRANSFORMATION",
		3: "PREPROCESSING_TYPE_FILTERING",
		4: "PREPROCESSING_TYPE_AGGREGATION",
		5: "PREPROCESSING_TYPE_SHARDING",
		6: "PREPROCESSING_TYPE_NORMALIZATION",
		7: "PREPROCESSING_TYPE_FEATURE_EXTRACT",
	}
	PreprocessingType_value = map[string]int32{
		"PREPROCESSING_TYPE_UNKNOWN":         0,
		"PREPROCESSING_TYPE_AUGMENTATION":    1,
		"PREPROCESSING_TYPE_TRANSFORMATION":  2,
		"PREPROCESSING_TYPE_FILTERING":       3,
		"PREPROCESSING_TYPE_AGGREGATION":     4,
		"PREPROCESSING_TYPE_SHARDING":        5,
		"PREPROCESSING_TYPE_NORMALIZATION":   6,
		"PREPROCESSING_TYPE_FEATURE_EXTRACT": 7,
	}
)

func (x PreprocessingType) Enum() *PreprocessingType {
	p := new(PreprocessingType)
	*p = x
	return p
}

func (x PreprocessingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PreprocessingType) Descriptor() protoreflect.EnumDescriptor {
	return file_apollo_proto_enumTypes[5].Descriptor()
}

func (PreprocessingType) Type() protoreflect.EnumType {
	return &file_apollo_proto_enumTypes[5]
}

func (x PreprocessingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PreprocessingType.Descriptor instead.
func (PreprocessingType) EnumDescriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{5}
}

type SchedulingPolicyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PodName        string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace   string                 `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	PodUid         string                 `protobuf:"bytes,3,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	PodLabels      map[string]string      `protobuf:"bytes,4,rep,name=pod_labels,json=podLabels,proto3" json:"pod_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PodAnnotations map[string]string      `protobuf:"bytes,5,rep,name=pod_annotations,json=podAnnotations,proto3" json:"pod_annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SchedulingPolicyRequest) Reset() {
	*x = SchedulingPolicyRequest{}
	mi := &file_apollo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulingPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulingPolicyRequest) ProtoMessage() {}

func (x *SchedulingPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulingPolicyRequest.ProtoReflect.Descriptor instead.
func (*SchedulingPolicyRequest) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{0}
}

func (x *SchedulingPolicyRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *SchedulingPolicyRequest) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *SchedulingPolicyRequest) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *SchedulingPolicyRequest) GetPodLabels() map[string]string {
	if x != nil {
		return x.PodLabels
	}
	return nil
}

func (x *SchedulingPolicyRequest) GetPodAnnotations() map[string]string {
	if x != nil {
		return x.PodAnnotations
	}
	return nil
}

type SchedulingPolicy struct {
	state                protoimpl.MessageState        `protogen:"open.v1"`
	RequestId            string                        `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PodName              string                        `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace         string                        `protobuf:"bytes,3,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	Decision             SchedulingDecision            `protobuf:"varint,4,opt,name=decision,proto3,enum=apollo.SchedulingDecision" json:"decision,omitempty"`
	NodePreferences      []*NodePreference             `protobuf:"bytes,5,rep,name=node_preferences,json=nodePreferences,proto3" json:"node_preferences,omitempty"`
	ResourceRequirements *ComputedResourceRequirements `protobuf:"bytes,6,opt,name=resource_requirements,json=resourceRequirements,proto3" json:"resource_requirements,omitempty"`
	StorageRequirements  *StorageRequirements          `protobuf:"bytes,7,opt,name=storage_requirements,json=storageRequirements,proto3" json:"storage_requirements,omitempty"`
	Constraints          []*SchedulingConstraint       `protobuf:"bytes,8,rep,name=constraints,proto3" json:"constraints,omitempty"`
	Priority             int32                         `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	AllowPreemption      bool                          `protobuf:"varint,10,opt,name=allow_preemption,json=allowPreemption,proto3" json:"allow_preemption,omitempty"`
	AffinityRules        []*AffinityRule               `protobuf:"bytes,11,rep,name=affinity_rules,json=affinityRules,proto3" json:"affinity_rules,omitempty"`
	Reason               string                        `protobuf:"bytes,12,opt,name=reason,proto3" json:"reason,omitempty"`
	PluginWeights        *PluginWeights                `protobuf:"bytes,13,opt,name=plugin_weights,json=pluginWeights,proto3" json:"plugin_weights,omitempty"`
	WorkloadSignature    *WorkloadSignatureInfo        `protobuf:"bytes,20,opt,name=workload_signature,json=workloadSignature,proto3" json:"workload_signature,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SchedulingPolicy) Reset() {
	*x = SchedulingPolicy{}
	mi := &file_apollo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulingPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulingPolicy) ProtoMessage() {}

func (x *SchedulingPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulingPolicy.ProtoReflect.Descriptor instead.
func (*SchedulingPolicy) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{1}
}

func (x *SchedulingPolicy) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SchedulingPolicy) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *SchedulingPolicy) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *SchedulingPolicy) GetDecision() SchedulingDecision {
	if x != nil {
		return x.Decision
	}
	return SchedulingDecision_SCHEDULING_DECISION_UNSPECIFIED
}

func (x *SchedulingPolicy) GetNodePreferences() []*NodePreference {
	if x != nil {
		return x.NodePreferences
	}
	return nil
}

func (x *SchedulingPolicy) GetResourceRequirements() *ComputedResourceRequirements {
	if x != nil {
		return x.ResourceRequirements
	}
	return nil
}

func (x *SchedulingPolicy) GetStorageRequirements() *StorageRequirements {
	if x != nil {
		return x.StorageRequirements
	}
	return nil
}

func (x *SchedulingPolicy) GetConstraints() []*SchedulingConstraint {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *SchedulingPolicy) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SchedulingPolicy) GetAllowPreemption() bool {
	if x != nil {
		return x.AllowPreemption
	}
	return false
}

func (x *SchedulingPolicy) GetAffinityRules() []*AffinityRule {
	if x != nil {
		return x.AffinityRules
	}
	return nil
}

func (x *SchedulingPolicy) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SchedulingPolicy) GetPluginWeights() *PluginWeights {
	if x != nil {
		return x.PluginWeights
	}
	return nil
}

func (x *SchedulingPolicy) GetWorkloadSignature() *WorkloadSignatureInfo {
	if x != nil {
		return x.WorkloadSignature
	}
	return nil
}

// PluginWeights contains dynamic weights for KETI scoring plugins
// Weights are 0.0-1.0, applied by scheduler to adjust plugin importance
type PluginWeights struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DataLocalityAware  float32                `protobuf:"fixed32,1,opt,name=data_locality_aware,json=dataLocalityAware,proto3" json:"data_locality_aware,omitempty"`    // DataLocalityAware plugin weight
	StorageTierAware   float32                `protobuf:"fixed32,2,opt,name=storage_tier_aware,json=storageTierAware,proto3" json:"storage_tier_aware,omitempty"`       // StorageTierAware plugin weight
	IoPatternBased     float32                `protobuf:"fixed32,3,opt,name=io_pattern_based,json=ioPatternBased,proto3" json:"io_pattern_based,omitempty"`             // IOPatternBased plugin weight
	KueueAware         float32                `protobuf:"fixed32,4,opt,name=kueue_aware,json=kueueAware,proto3" json:"kueue_aware,omitempty"`                           // KueueAware plugin weight
	PipelineStageAware float32                `protobuf:"fixed32,5,opt,name=pipeline_stage_aware,json=pipelineStageAware,proto3" json:"pipeline_stage_aware,omitempty"` // PipelineStageAware plugin weight
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PluginWeights) Reset() {
	*x = PluginWeights{}
	mi := &file_apollo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginWeights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginWeights) ProtoMessage() {}

func (x *PluginWeights) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginWeights.ProtoReflect.Descriptor instead.
func (*PluginWeights) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{2}
}

func (x *PluginWeights) GetDataLocalityAware() float32 {
	if x != nil {
		return x.DataLocalityAware
	}
	return 0
}

func (x *PluginWeights) GetStorageTierAware() float32 {
	if x != nil {
		return x.StorageTierAware
	}
	return 0
}

func (x *PluginWeights) GetIoPatternBased() float32 {
	if x != nil {
		return x.IoPatternBased
	}
	return 0
}

func (x *PluginWeights) GetKueueAware() float32 {
	if x != nil {
		return x.KueueAware
	}
	return 0
}

func (x *PluginWeights) GetPipelineStageAware() float32 {
	if x != nil {
		return x.PipelineStageAware
	}
	return 0
}

type WorkloadSignatureInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkloadType       WorkloadType           `protobuf:"varint,1,opt,name=workload_type,json=workloadType,proto3,enum=apollo.WorkloadType" json:"workload_type,omitempty"`
	CurrentStage       PipelineStage          `protobuf:"varint,2,opt,name=current_stage,json=currentStage,proto3,enum=apollo.PipelineStage" json:"current_stage,omitempty"`
	IoPattern          IOPattern              `protobuf:"varint,3,opt,name=io_pattern,json=ioPattern,proto3,enum=apollo.IOPattern" json:"io_pattern,omitempty"`
	Confidence         float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Framework          string                 `protobuf:"bytes,5,opt,name=framework,proto3" json:"framework,omitempty"`
	FrameworkVersion   string                 `protobuf:"bytes,6,opt,name=framework_version,json=frameworkVersion,proto3" json:"framework_version,omitempty"`
	IsGpuWorkload      bool                   `protobuf:"varint,7,opt,name=is_gpu_workload,json=isGpuWorkload,proto3" json:"is_gpu_workload,omitempty"`
	IsDistributed      bool                   `protobuf:"varint,8,opt,name=is_distributed,json=isDistributed,proto3" json:"is_distributed,omitempty"`
	IsPipeline         bool                   `protobuf:"varint,9,opt,name=is_pipeline,json=isPipeline,proto3" json:"is_pipeline,omitempty"`
	PipelineStep       string                 `protobuf:"bytes,10,opt,name=pipeline_step,json=pipelineStep,proto3" json:"pipeline_step,omitempty"`
	EstimatedBatchSize int32                  `protobuf:"varint,11,opt,name=estimated_batch_size,json=estimatedBatchSize,proto3" json:"estimated_batch_size,omitempty"`
	PreprocessingType  PreprocessingType      `protobuf:"varint,12,opt,name=preprocessing_type,json=preprocessingType,proto3,enum=apollo.PreprocessingType" json:"preprocessing_type,omitempty"`
	DatasetName        string                 `protobuf:"bytes,13,opt,name=dataset_name,json=datasetName,proto3" json:"dataset_name,omitempty"`
	DataLocations      []string               `protobuf:"bytes,14,rep,name=data_locations,json=dataLocations,proto3" json:"data_locations,omitempty"`
	CachedOnNodes      []string               `protobuf:"bytes,15,rep,name=cached_on_nodes,json=cachedOnNodes,proto3" json:"cached_on_nodes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkloadSignatureInfo) Reset() {
	*x = WorkloadSignatureInfo{}
	mi := &file_apollo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadSignatureInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSignatureInfo) ProtoMessage() {}

func (x *WorkloadSignatureInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSignatureInfo.ProtoReflect.Descriptor instead.
func (*WorkloadSignatureInfo) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{3}
}

func (x *WorkloadSignatureInfo) GetWorkloadType() WorkloadType {
	if x != nil {
		return x.WorkloadType
	}
	return WorkloadType_WORKLOAD_TYPE_UNKNOWN
}

func (x *WorkloadSignatureInfo) GetCurrentStage() PipelineStage {
	if x != nil {
		return x.CurrentStage
	}
	return PipelineStage_PIPELINE_STAGE_UNKNOWN
}

func (x *WorkloadSignatureInfo) GetIoPattern() IOPattern {
	if x != nil {
		return x.IoPattern
	}
	return IOPattern_IO_PATTERN_UNKNOWN
}

func (x *WorkloadSignatureInfo) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *WorkloadSignatureInfo) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *WorkloadSignatureInfo) GetFrameworkVersion() string {
	if x != nil {
		return x.FrameworkVersion
	}
	return ""
}

func (x *WorkloadSignatureInfo) GetIsGpuWorkload() bool {
	if x != nil {
		return x.IsGpuWorkload
	}
	return false
}

func (x *WorkloadSignatureInfo) GetIsDistributed() bool {
	if x != nil {
		return x.IsDistributed
	}
	return false
}

func (x *WorkloadSignatureInfo) GetIsPipeline() bool {
	if x != nil {
		return x.IsPipeline
	}
	return false
}

func (x *WorkloadSignatureInfo) GetPipelineStep() string {
	if x != nil {
		return x.PipelineStep
	}
	return ""
}

func (x *WorkloadSignatureInfo) GetEstimatedBatchSize() int32 {
	if x != nil {
		return x.EstimatedBatchSize
	}
	return 0
}

func (x *WorkloadSignatureInfo) GetPreprocessingType() PreprocessingType {
	if x != nil {
		return x.PreprocessingType
	}
	return PreprocessingType_PREPROCESSING_TYPE_UNKNOWN
}

func (x *WorkloadSignatureInfo) GetDatasetName() string {
	if x != nil {
		return x.DatasetName
	}
	return ""
}

func (x *WorkloadSignatureInfo) GetDataLocations() []string {
	if x != nil {
		return x.DataLocations
	}
	return nil
}

func (x *WorkloadSignatureInfo) GetCachedOnNodes() []string {
	if x != nil {
		return x.CachedOnNodes
	}
	return nil
}

type NodePreference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodePreference) Reset() {
	*x = NodePreference{}
	mi := &file_apollo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePreference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePreference) ProtoMessage() {}

func (x *NodePreference) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePreference.ProtoReflect.Descriptor instead.
func (*NodePreference) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{4}
}

func (x *NodePreference) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodePreference) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *NodePreference) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ComputedResourceRequirements struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CpuCores               float64                `protobuf:"fixed64,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryBytes            int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	StorageBytes           int64                  `protobuf:"varint,3,opt,name=storage_bytes,json=storageBytes,proto3" json:"storage_bytes,omitempty"`
	GpuCount               int32                  `protobuf:"varint,4,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`
	ExpectedIops           int64                  `protobuf:"varint,5,opt,name=expected_iops,json=expectedIops,proto3" json:"expected_iops,omitempty"`
	ExpectedThroughputMbps int64                  `protobuf:"varint,6,opt,name=expected_throughput_mbps,json=expectedThroughputMbps,proto3" json:"expected_throughput_mbps,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ComputedResourceRequirements) Reset() {
	*x = ComputedResourceRequirements{}
	mi := &file_apollo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputedResourceRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputedResourceRequirements) ProtoMessage() {}

func (x *ComputedResourceRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputedResourceRequirements.ProtoReflect.Descriptor instead.
func (*ComputedResourceRequirements) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{5}
}

func (x *ComputedResourceRequirements) GetCpuCores() float64 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *ComputedResourceRequirements) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ComputedResourceRequirements) GetStorageBytes() int64 {
	if x != nil {
		return x.StorageBytes
	}
	return 0
}

func (x *ComputedResourceRequirements) GetGpuCount() int32 {
	if x != nil {
		return x.GpuCount
	}
	return 0
}

func (x *ComputedResourceRequirements) GetExpectedIops() int64 {
	if x != nil {
		return x.ExpectedIops
	}
	return 0
}

func (x *ComputedResourceRequirements) GetExpectedThroughputMbps() int64 {
	if x != nil {
		return x.ExpectedThroughputMbps
	}
	return 0
}

type StorageRequirements struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StorageClass      StorageClass           `protobuf:"varint,1,opt,name=storage_class,json=storageClass,proto3,enum=apollo.StorageClass" json:"storage_class,omitempty"`
	SizeBytes         int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	MinIops           int64                  `protobuf:"varint,3,opt,name=min_iops,json=minIops,proto3" json:"min_iops,omitempty"`
	MinThroughputMbps int64                  `protobuf:"varint,4,opt,name=min_throughput_mbps,json=minThroughputMbps,proto3" json:"min_throughput_mbps,omitempty"`
	ExpectedIoPattern IOPattern              `protobuf:"varint,5,opt,name=expected_io_pattern,json=expectedIoPattern,proto3,enum=apollo.IOPattern" json:"expected_io_pattern,omitempty"`
	RequiresCsd       bool                   `protobuf:"varint,6,opt,name=requires_csd,json=requiresCsd,proto3" json:"requires_csd,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StorageRequirements) Reset() {
	*x = StorageRequirements{}
	mi := &file_apollo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageRequirements) ProtoMessage() {}

func (x *StorageRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageRequirements.ProtoReflect.Descriptor instead.
func (*StorageRequirements) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{6}
}

func (x *StorageRequirements) GetStorageClass() StorageClass {
	if x != nil {
		return x.StorageClass
	}
	return StorageClass_STORAGE_CLASS_UNSPECIFIED
}

func (x *StorageRequirements) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *StorageRequirements) GetMinIops() int64 {
	if x != nil {
		return x.MinIops
	}
	return 0
}

func (x *StorageRequirements) GetMinThroughputMbps() int64 {
	if x != nil {
		return x.MinThroughputMbps
	}
	return 0
}

func (x *StorageRequirements) GetExpectedIoPattern() IOPattern {
	if x != nil {
		return x.ExpectedIoPattern
	}
	return IOPattern_IO_PATTERN_UNKNOWN
}

func (x *StorageRequirements) GetRequiresCsd() bool {
	if x != nil {
		return x.RequiresCsd
	}
	return false
}

type SchedulingConstraint struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConstraintType string                 `protobuf:"bytes,1,opt,name=constraint_type,json=constraintType,proto3" json:"constraint_type,omitempty"`
	Key            string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Operator       string                 `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Values         []string               `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SchedulingConstraint) Reset() {
	*x = SchedulingConstraint{}
	mi := &file_apollo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulingConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulingConstraint) ProtoMessage() {}

func (x *SchedulingConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulingConstraint.ProtoReflect.Descriptor instead.
func (*SchedulingConstraint) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{7}
}

func (x *SchedulingConstraint) GetConstraintType() string {
	if x != nil {
		return x.ConstraintType
	}
	return ""
}

func (x *SchedulingConstraint) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SchedulingConstraint) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *SchedulingConstraint) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type AffinityRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleType      string                 `protobuf:"bytes,1,opt,name=rule_type,json=ruleType,proto3" json:"rule_type,omitempty"`
	TopologyKey   string                 `protobuf:"bytes,2,opt,name=topology_key,json=topologyKey,proto3" json:"topology_key,omitempty"`
	TargetLabels  []string               `protobuf:"bytes,3,rep,name=target_labels,json=targetLabels,proto3" json:"target_labels,omitempty"`
	IsRequired    bool                   `protobuf:"varint,4,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	Weight        int32                  `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AffinityRule) Reset() {
	*x = AffinityRule{}
	mi := &file_apollo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AffinityRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffinityRule) ProtoMessage() {}

func (x *AffinityRule) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffinityRule.ProtoReflect.Descriptor instead.
func (*AffinityRule) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{8}
}

func (x *AffinityRule) GetRuleType() string {
	if x != nil {
		return x.RuleType
	}
	return ""
}

func (x *AffinityRule) GetTopologyKey() string {
	if x != nil {
		return x.TopologyKey
	}
	return ""
}

func (x *AffinityRule) GetTargetLabels() []string {
	if x != nil {
		return x.TargetLabels
	}
	return nil
}

func (x *AffinityRule) GetIsRequired() bool {
	if x != nil {
		return x.IsRequired
	}
	return false
}

func (x *AffinityRule) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type SchedulingResult struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RequestId            string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PodName              string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace         string                 `protobuf:"bytes,3,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	ScheduledNode        string                 `protobuf:"bytes,4,opt,name=scheduled_node,json=scheduledNode,proto3" json:"scheduled_node,omitempty"`
	Success              bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	FailureReason        string                 `protobuf:"bytes,6,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	SchedulingDurationMs int64                  `protobuf:"varint,7,opt,name=scheduling_duration_ms,json=schedulingDurationMs,proto3" json:"scheduling_duration_ms,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SchedulingResult) Reset() {
	*x = SchedulingResult{}
	mi := &file_apollo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulingResult) ProtoMessage() {}

func (x *SchedulingResult) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulingResult.ProtoReflect.Descriptor instead.
func (*SchedulingResult) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{9}
}

func (x *SchedulingResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SchedulingResult) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *SchedulingResult) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *SchedulingResult) GetScheduledNode() string {
	if x != nil {
		return x.ScheduledNode
	}
	return ""
}

func (x *SchedulingResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SchedulingResult) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *SchedulingResult) GetSchedulingDurationMs() int64 {
	if x != nil {
		return x.SchedulingDurationMs
	}
	return 0
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_apollo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apollo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_apollo_proto_rawDescGZIP(), []int{10}
}

func (x *ReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReportResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_apollo_proto protoreflect.FileDescriptor

const file_apollo_proto_rawDesc = "" +
	"\n" +
	"\fapollo.proto\x12\x06apollo\"\xa0\x03\n" +
	"\x17SchedulingPolicyRequest\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x02 \x01(\tR\fpodNamespace\x12\x17\n" +
	"\apod_uid\x18\x03 \x01(\tR\x06podUid\x12M\n" +
	"\n" +
	"pod_labels\x18\x04 \x03(\v2..apollo.SchedulingPolicyRequest.PodLabelsEntryR\tpodLabels\x12\\\n" +
	"\x0fpod_annotations\x18\x05 \x03(\v23.apollo.SchedulingPolicyRequest.PodAnnotationsEntryR\x0epodAnnotations\x1a<\n" +
	"\x0ePodLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13PodAnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xff\x05\n" +
	"\x10SchedulingPolicy\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x03 \x01(\tR\fpodNamespace\x126\n" +
	"\bdecision\x18\x04 \x01(\x0e2\x1a.apollo.SchedulingDecisionR\bdecision\x12A\n" +
	"\x10node_preferences\x18\x05 \x03(\v2\x16.apollo.NodePreferenceR\x0fnodePreferences\x12Y\n" +
	"\x15resource_requirements\x18\x06 \x01(\v2$.apollo.ComputedResourceRequirementsR\x14resourceRequirements\x12N\n" +
	"\x14storage_requirements\x18\a \x01(\v2\x1b.apollo.StorageRequirementsR\x13storageRequirements\x12>\n" +
	"\vconstraints\x18\b \x03(\v2\x1c.apollo.SchedulingConstraintR\vconstraints\x12\x1a\n" +
	"\bpriority\x18\t \x01(\x05R\bpriority\x12)\n" +
	"\x10allow_preemption\x18\n" +
	" \x01(\bR\x0fallowPreemption\x12;\n" +
	"\x0eaffinity_rules\x18\v \x03(\v2\x14.apollo.AffinityRuleR\raffinityRules\x12\x16\n" +
	"\x06reason\x18\f \x01(\tR\x06reason\x12<\n" +
	"\x0eplugin_weights\x18\r \x01(\v2\x15.apollo.PluginWeightsR\rpluginWeights\x12L\n" +
	"\x12workload_signature\x18\x14 \x01(\v2\x1d.apollo.WorkloadSignatureInfoR\x11workloadSignature\"\xea\x01\n" +
	"\rPluginWeights\x12.\n" +
	"\x13data_locality_aware\x18\x01 \x01(\x02R\x11dataLocalityAware\x12,\n" +
	"\x12storage_tier_aware\x18\x02 \x01(\x02R\x10storageTierAware\x12(\n" +
	"\x10io_pattern_based\x18\x03 \x01(\x02R\x0eioPatternBased\x12\x1f\n" +
	"\vkueue_aware\x18\x04 \x01(\x02R\n" +
	"kueueAware\x120\n" +
	"\x14pipeline_stage_aware\x18\x05 \x01(\x02R\x12pipelineStageAware\"\xae\x05\n" +
	"\x15WorkloadSignatureInfo\x129\n" +
	"\rworkload_type\x18\x01 \x01(\x0e2\x14.apollo.WorkloadTypeR\fworkloadType\x12:\n" +
	"\rcurrent_stage\x18\x02 \x01(\x0e2\x15.apollo.PipelineStageR\fcurrentStage\x120\n" +
	"\n" +
	"io_pattern\x18\x03 \x01(\x0e2\x11.apollo.IOPatternR\tioPattern\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12\x1c\n" +
	"\tframework\x18\x05 \x01(\tR\tframework\x12+\n" +
	"\x11framework_version\x18\x06 \x01(\tR\x10frameworkVersion\x12&\n" +
	"\x0fis_gpu_workload\x18\a \x01(\bR\risGpuWorkload\x12%\n" +
	"\x0eis_distributed\x18\b \x01(\bR\risDistributed\x12\x1f\n" +
	"\vis_pipeline\x18\t \x01(\bR\n" +
	"isPipeline\x12#\n" +
	"\rpipeline_step\x18\n" +
	" \x01(\tR\fpipelineStep\x120\n" +
	"\x14estimated_batch_size\x18\v \x01(\x05R\x12estimatedBatchSize\x12H\n" +
	"\x12preprocessing_type\x18\f \x01(\x0e2\x19.apollo.PreprocessingTypeR\x11preprocessingType\x12!\n" +
	"\fdataset_name\x18\r \x01(\tR\vdatasetName\x12%\n" +
	"\x0edata_locations\x18\x0e \x03(\tR\rdataLocations\x12&\n" +
	"\x0fcached_on_nodes\x18\x0f \x03(\tR\rcachedOnNodes\"[\n" +
	"\x0eNodePreference\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xff\x01\n" +
	"\x1cComputedResourceRequirements\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x01R\bcpuCores\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12#\n" +
	"\rstorage_bytes\x18\x03 \x01(\x03R\fstorageBytes\x12\x1b\n" +
	"\tgpu_count\x18\x04 \x01(\x05R\bgpuCount\x12#\n" +
	"\rexpected_iops\x18\x05 \x01(\x03R\fexpectedIops\x128\n" +
	"\x18expected_throughput_mbps\x18\x06 \x01(\x03R\x16expectedThroughputMbps\"\xa0\x02\n" +
	"\x13StorageRequirements\x129\n" +
	"\rstorage_class\x18\x01 \x01(\x0e2\x14.apollo.StorageClassR\fstorageClass\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12\x19\n" +
	"\bmin_iops\x18\x03 \x01(\x03R\aminIops\x12.\n" +
	"\x13min_throughput_mbps\x18\x04 \x01(\x03R\x11minThroughputMbps\x12A\n" +
	"\x13expected_io_pattern\x18\x05 \x01(\x0e2\x11.apollo.IOPatternR\x11expectedIoPattern\x12!\n" +
	"\frequires_csd\x18\x06 \x01(\bR\vrequiresCsd\"\x85\x01\n" +
	"\x14SchedulingConstraint\x12'\n" +
	"\x0fconstraint_type\x18\x01 \x01(\tR\x0econstraintType\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1a\n" +
	"\boperator\x18\x03 \x01(\tR\boperator\x12\x16\n" +
	"\x06values\x18\x04 \x03(\tR\x06values\"\xac\x01\n" +
	"\fAffinityRule\x12\x1b\n" +
	"\trule_type\x18\x01 \x01(\tR\bruleType\x12!\n" +
	"\ftopology_key\x18\x02 \x01(\tR\vtopologyKey\x12#\n" +
	"\rtarget_labels\x18\x03 \x03(\tR\ftargetLabels\x12\x1f\n" +
	"\vis_required\x18\x04 \x01(\bR\n" +
	"isRequired\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x05R\x06weight\"\x8f\x02\n" +
	"\x10SchedulingResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x03 \x01(\tR\fpodNamespace\x12%\n" +
	"\x0escheduled_node\x18\x04 \x01(\tR\rscheduledNode\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12%\n" +
	"\x0efailure_reason\x18\x06 \x01(\tR\rfailureReason\x124\n" +
	"\x16scheduling_duration_ms\x18\a \x01(\x03R\x14schedulingDurationMs\"c\n" +
	"\x0eReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId*\xd8\x01\n" +
	"\x12SchedulingDecision\x12#\n" +
	"\x1fSCHEDULING_DECISION_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SCHEDULING_DECISION_ALLOW\x10\x01\x12\x1e\n" +
	"\x1aSCHEDULING_DECISION_PREFER\x10\x02\x12\x1f\n" +
	"\x1bSCHEDULING_DECISION_REQUIRE\x10\x03\x12\x1d\n" +
	"\x19SCHEDULING_DECISION_DELAY\x10\x04\x12\x1e\n" +
	"\x1aSCHEDULING_DECISION_REJECT\x10\x05*\xe0\x01\n" +
	"\fWorkloadType\x12\x19\n" +
	"\x15WORKLOAD_TYPE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13WORKLOAD_TYPE_IMAGE\x10\x01\x12\x16\n" +
	"\x12WORKLOAD_TYPE_TEXT\x10\x02\x12\x19\n" +
	"\x15WORKLOAD_TYPE_TABULAR\x10\x03\x12\x17\n" +
	"\x13WORKLOAD_TYPE_AUDIO\x10\x04\x12\x17\n" +
	"\x13WORKLOAD_TYPE_VIDEO\x10\x05\x12\x1c\n" +
	"\x18WORKLOAD_TYPE_MULTIMODAL\x10\x06\x12\x19\n" +
	"\x15WORKLOAD_TYPE_GENERIC\x10\a*\xa6\x02\n" +
	"\rPipelineStage\x12\x1a\n" +
	"\x16PIPELINE_STAGE_UNKNOWN\x10\x00\x12\x1f\n" +
	"\x1bPIPELINE_STAGE_DATA_LOADING\x10\x01\x12 \n" +
	"\x1cPIPELINE_STAGE_PREPROCESSING\x10\x02\x12\x1b\n" +
	"\x17PIPELINE_STAGE_TRAINING\x10\x03\x12\x1d\n" +
	"\x19PIPELINE_STAGE_VALIDATION\x10\x04\x12\x1c\n" +
	"\x18PIPELINE_STAGE_INFERENCE\x10\x05\x12!\n" +
	"\x1dPIPELINE_STAGE_POSTPROCESSING\x10\x06\x12 \n" +
	"\x1cPIPELINE_STAGE_CHECKPOINTING\x10\a\x12\x17\n" +
	"\x13PIPELINE_STAGE_IDLE\x10\b*\xbc\x01\n" +
	"\tIOPattern\x12\x16\n" +
	"\x12IO_PATTERN_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15IO_PATTERN_READ_HEAVY\x10\x01\x12\x1a\n" +
	"\x16IO_PATTERN_WRITE_HEAVY\x10\x02\x12\x17\n" +
	"\x13IO_PATTERN_BALANCED\x10\x03\x12\x19\n" +
	"\x15IO_PATTERN_SEQUENTIAL\x10\x04\x12\x15\n" +
	"\x11IO_PATTERN_RANDOM\x10\x05\x12\x15\n" +
	"\x11IO_PATTERN_BURSTY\x10\x06*\xb0\x01\n" +
	"\fStorageClass\x12\x1d\n" +
	"\x19STORAGE_CLASS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16STORAGE_CLASS_STANDARD\x10\x01\x12\x16\n" +
	"\x12STORAGE_CLASS_FAST\x10\x02\x12\x1c\n" +
	"\x18STORAGE_CLASS_ULTRA_FAST\x10\x03\x12\x15\n" +
	"\x11STORAGE_CLASS_CSD\x10\x04\x12\x18\n" +
	"\x14STORAGE_CLASS_MEMORY\x10\x05*\xb4\x02\n" +
	"\x11PreprocessingType\x12\x1e\n" +
	"\x1aPREPROCESSING_TYPE_UNKNOWN\x10\x00\x12#\n" +
	"\x1fPREPROCESSING_TYPE_AUGMENTATION\x10\x01\x12%\n" +
	"!PREPROCESSING_TYPE_TRANSFORMATION\x10\x02\x12 \n" +
	"\x1cPREPROCESSING_TYPE_FILTERING\x10\x03\x12\"\n" +
	"\x1ePREPROCESSING_TYPE_AGGREGATION\x10\x04\x12\x1f\n" +
	"\x1bPREPROCESSING_TYPE_SHARDING\x10\x05\x12$\n" +
	" PREPROCESSING_TYPE_NORMALIZATION\x10\x06\x12&\n" +
	"\"PREPROCESSING_TYPE_FEATURE_EXTRACT\x10\a2\xb7\x01\n" +
	"\x17SchedulingPolicyService\x12P\n" +
	"\x13GetSchedulingPolicy\x12\x1f.apollo.SchedulingPolicyRequest\x1a\x18.apollo.SchedulingPolicy\x12J\n" +
	"\x16ReportSchedulingResult\x12\x18.apollo.SchedulingResult\x1a\x16.apollo.ReportResponseB+Z)keti/ai-storage-scheduler/internal/apollob\x06proto3"

var (
	file_apollo_proto_rawDescOnce sync.Once
	file_apollo_proto_rawDescData []byte
)

func file_apollo_proto_rawDescGZIP() []byte {
	file_apollo_proto_rawDescOnce.Do(func() {
		file_apollo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apollo_proto_rawDesc), len(file_apollo_proto_rawDesc)))
	})
	return file_apollo_proto_rawDescData
}

var file_apollo_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_apollo_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_apollo_proto_goTypes = []any{
	(SchedulingDecision)(0),              // 0: apollo.SchedulingDecision
	(WorkloadType)(0),                    // 1: apollo.WorkloadType
	(PipelineStage)(0),                   // 2: apollo.PipelineStage
	(IOPattern)(0),                       // 3: apollo.IOPattern
	(StorageClass)(0),                    // 4: apollo.StorageClass
	(PreprocessingType)(0),               // 5: apollo.PreprocessingType
	(*SchedulingPolicyRequest)(nil),      // 6: apollo.SchedulingPolicyRequest
	(*SchedulingPolicy)(nil),             // 7: apollo.SchedulingPolicy
	(*PluginWeights)(nil),                // 8: apollo.PluginWeights
	(*WorkloadSignatureInfo)(nil),        // 9: apollo.WorkloadSignatureInfo
	(*NodePreference)(nil),               // 10: apollo.NodePreference
	(*ComputedResourceRequirements)(nil), // 11: apollo.ComputedResourceRequirements
	(*StorageRequirements)(nil),          // 12: apollo.StorageRequirements
	(*SchedulingConstraint)(nil),         // 13: apollo.SchedulingConstraint
	(*AffinityRule)(nil),                 // 14: apollo.AffinityRule
	(*SchedulingResult)(nil),             // 15: apollo.SchedulingResult
	(*ReportResponse)(nil),               // 16: apollo.ReportResponse
	nil,                                  // 17: apollo.SchedulingPolicyRequest.PodLabelsEntry
	nil,                                  // 18: apollo.SchedulingPolicyRequest.PodAnnotationsEntry
}
var file_apollo_proto_depIdxs = []int32{
	17, // 0: apollo.SchedulingPolicyRequest.pod_labels:type_name -> apollo.SchedulingPolicyRequest.PodLabelsEntry
	18, // 1: apollo.SchedulingPolicyRequest.pod_annotations:type_name -> apollo.SchedulingPolicyRequest.PodAnnotationsEntry
	0,  // 2: apollo.SchedulingPolicy.decision:type_name -> apollo.SchedulingDecision
	10, // 3: apollo.SchedulingPolicy.node_preferences:type_name -> apollo.NodePreference
	11, // 4: apollo.SchedulingPolicy.resource_requirements:type_name -> apollo.ComputedResourceRequirements
	12, // 5: apollo.SchedulingPolicy.storage_requirements:type_name -> apollo.StorageRequirements
	13, // 6: apollo.SchedulingPolicy.constraints:type_name -> apollo.SchedulingConstraint
	14, // 7: apollo.SchedulingPolicy.affinity_rules:type_name -> apollo.AffinityRule
	8,  // 8: apollo.SchedulingPolicy.plugin_weights:type_name -> apollo.PluginWeights
	9,  // 9: apollo.SchedulingPolicy.workload_signature:type_name -> apollo.WorkloadSignatureInfo
	1,  // 10: apollo.WorkloadSignatureInfo.workload_type:type_name -> apollo.WorkloadType
	2,  // 11: apollo.WorkloadSignatureInfo.current_stage:type_name -> apollo.PipelineStage
	3,  // 12: apollo.WorkloadSignatureInfo.io_pattern:type_name -> apollo.IOPattern
	5,  // 13: apollo.WorkloadSignatureInfo.preprocessing_type:type_name -> apollo.PreprocessingType
	4,  // 14: apollo.StorageRequirements.storage_class:type_name -> apollo.StorageClass
	3,  // 15: apollo.StorageRequirements.expected_io_pattern:type_name -> apollo.IOPattern
	6,  // 16: apollo.SchedulingPolicyService.GetSchedulingPolicy:input_type -> apollo.SchedulingPolicyRequest
	15, // 17: apollo.SchedulingPolicyService.ReportSchedulingResult:input_type -> apollo.SchedulingResult
	7,  // 18: apollo.SchedulingPolicyService.GetSchedulingPolicy:output_type -> apollo.SchedulingPolicy
	16, // 19: apollo.SchedulingPolicyService.ReportSchedulingResult:output_type -> apollo.ReportResponse
	18, // [18:20] is the sub-list for method output_type
	16, // [16:18] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_apollo_proto_init() }
func file_apollo_proto_init() {
	if File_apollo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apollo_proto_rawDesc), len(file_apollo_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apollo_proto_goTypes,
		DependencyIndexes: file_apollo_proto_depIdxs,
		EnumInfos:         file_apollo_proto_enumTypes,
		MessageInfos:      file_apollo_proto_msgTypes,
	}.Build()
	File_apollo_proto = out.File
	file_apollo_proto_goTypes = nil
	file_apollo_proto_depIdxs = nil
}
