// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: hub.proto

package hubpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Wall-clock time in milliseconds since Unix epoch (UTC).
// pod_namespace / pod_name 이 비어 있으면 노드 집계 샘플, 있으면 해당 Pod 전용(메트릭 서버 기준 사용률).
type ResourceSnapshot struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixMs      int64                  `protobuf:"varint,1,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	CpuUtilization       float64                `protobuf:"fixed64,2,opt,name=cpu_utilization,json=cpuUtilization,proto3" json:"cpu_utilization,omitempty"`
	MemoryUtilization    float64                `protobuf:"fixed64,3,opt,name=memory_utilization,json=memoryUtilization,proto3" json:"memory_utilization,omitempty"`
	GpuUtilization       float64                `protobuf:"fixed64,4,opt,name=gpu_utilization,json=gpuUtilization,proto3" json:"gpu_utilization,omitempty"`
	StorageIoUtilization float64                `protobuf:"fixed64,5,opt,name=storage_io_utilization,json=storageIoUtilization,proto3" json:"storage_io_utilization,omitempty"`
	PodNamespace         *string                `protobuf:"bytes,6,opt,name=pod_namespace,json=podNamespace,proto3,oneof" json:"pod_namespace,omitempty"`
	PodName              *string                `protobuf:"bytes,7,opt,name=pod_name,json=podName,proto3,oneof" json:"pod_name,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResourceSnapshot) Reset() {
	*x = ResourceSnapshot{}
	mi := &file_hub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSnapshot) ProtoMessage() {}

func (x *ResourceSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSnapshot.ProtoReflect.Descriptor instead.
func (*ResourceSnapshot) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceSnapshot) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *ResourceSnapshot) GetCpuUtilization() float64 {
	if x != nil {
		return x.CpuUtilization
	}
	return 0
}

func (x *ResourceSnapshot) GetMemoryUtilization() float64 {
	if x != nil {
		return x.MemoryUtilization
	}
	return 0
}

func (x *ResourceSnapshot) GetGpuUtilization() float64 {
	if x != nil {
		return x.GpuUtilization
	}
	return 0
}

func (x *ResourceSnapshot) GetStorageIoUtilization() float64 {
	if x != nil {
		return x.StorageIoUtilization
	}
	return 0
}

func (x *ResourceSnapshot) GetPodNamespace() string {
	if x != nil && x.PodNamespace != nil {
		return *x.PodNamespace
	}
	return ""
}

func (x *ResourceSnapshot) GetPodName() string {
	if x != nil && x.PodName != nil {
		return *x.PodName
	}
	return ""
}

type SubmitHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Snapshots     []*ResourceSnapshot    `protobuf:"bytes,2,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitHistoryRequest) Reset() {
	*x = SubmitHistoryRequest{}
	mi := &file_hub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitHistoryRequest) ProtoMessage() {}

func (x *SubmitHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitHistoryRequest.ProtoReflect.Descriptor instead.
func (*SubmitHistoryRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitHistoryRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *SubmitHistoryRequest) GetSnapshots() []*ResourceSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type SubmitHistoryResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Accepted           bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	SnapshotsProcessed int32                  `protobuf:"varint,2,opt,name=snapshots_processed,json=snapshotsProcessed,proto3" json:"snapshots_processed,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SubmitHistoryResponse) Reset() {
	*x = SubmitHistoryResponse{}
	mi := &file_hub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitHistoryResponse) ProtoMessage() {}

func (x *SubmitHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitHistoryResponse.ProtoReflect.Descriptor instead.
func (*SubmitHistoryResponse) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitHistoryResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubmitHistoryResponse) GetSnapshotsProcessed() int32 {
	if x != nil {
		return x.SnapshotsProcessed
	}
	return 0
}

type GetNodeHistoryRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	NodeName string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// If 0, no lower bound on time
	SinceUnixMs   int64 `protobuf:"varint,2,opt,name=since_unix_ms,json=sinceUnixMs,proto3" json:"since_unix_ms,omitempty"`
	MaxSnapshots  int32 `protobuf:"varint,3,opt,name=max_snapshots,json=maxSnapshots,proto3" json:"max_snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeHistoryRequest) Reset() {
	*x = GetNodeHistoryRequest{}
	mi := &file_hub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeHistoryRequest) ProtoMessage() {}

func (x *GetNodeHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetNodeHistoryRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{3}
}

func (x *GetNodeHistoryRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *GetNodeHistoryRequest) GetSinceUnixMs() int64 {
	if x != nil {
		return x.SinceUnixMs
	}
	return 0
}

func (x *GetNodeHistoryRequest) GetMaxSnapshots() int32 {
	if x != nil {
		return x.MaxSnapshots
	}
	return 0
}

type GetNodeHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*ResourceSnapshot    `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeHistoryResponse) Reset() {
	*x = GetNodeHistoryResponse{}
	mi := &file_hub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeHistoryResponse) ProtoMessage() {}

func (x *GetNodeHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetNodeHistoryResponse) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{4}
}

func (x *GetNodeHistoryResponse) GetSnapshots() []*ResourceSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_hub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{5}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeNames     []string               `protobuf:"bytes,1,rep,name=node_names,json=nodeNames,proto3" json:"node_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_hub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{6}
}

func (x *ListNodesResponse) GetNodeNames() []string {
	if x != nil {
		return x.NodeNames
	}
	return nil
}

type GetPodHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	PodNamespace  string                 `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	PodName       string                 `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	SinceUnixMs   int64                  `protobuf:"varint,4,opt,name=since_unix_ms,json=sinceUnixMs,proto3" json:"since_unix_ms,omitempty"`
	MaxSnapshots  int32                  `protobuf:"varint,5,opt,name=max_snapshots,json=maxSnapshots,proto3" json:"max_snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodHistoryRequest) Reset() {
	*x = GetPodHistoryRequest{}
	mi := &file_hub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodHistoryRequest) ProtoMessage() {}

func (x *GetPodHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetPodHistoryRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{7}
}

func (x *GetPodHistoryRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *GetPodHistoryRequest) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *GetPodHistoryRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *GetPodHistoryRequest) GetSinceUnixMs() int64 {
	if x != nil {
		return x.SinceUnixMs
	}
	return 0
}

func (x *GetPodHistoryRequest) GetMaxSnapshots() int32 {
	if x != nil {
		return x.MaxSnapshots
	}
	return 0
}

type GetPodHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*ResourceSnapshot    `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodHistoryResponse) Reset() {
	*x = GetPodHistoryResponse{}
	mi := &file_hub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodHistoryResponse) ProtoMessage() {}

func (x *GetPodHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetPodHistoryResponse) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{8}
}

func (x *GetPodHistoryResponse) GetSnapshots() []*ResourceSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

type ListPodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPodsRequest) Reset() {
	*x = ListPodsRequest{}
	mi := &file_hub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPodsRequest) ProtoMessage() {}

func (x *ListPodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPodsRequest.ProtoReflect.Descriptor instead.
func (*ListPodsRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{9}
}

type PodKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	PodNamespace  string                 `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	PodName       string                 `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodKey) Reset() {
	*x = PodKey{}
	mi := &file_hub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodKey) ProtoMessage() {}

func (x *PodKey) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodKey.ProtoReflect.Descriptor instead.
func (*PodKey) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{10}
}

func (x *PodKey) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *PodKey) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *PodKey) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

type ListPodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pods          []*PodKey              `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPodsResponse) Reset() {
	*x = ListPodsResponse{}
	mi := &file_hub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPodsResponse) ProtoMessage() {}

func (x *ListPodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPodsResponse.ProtoReflect.Descriptor instead.
func (*ListPodsResponse) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{11}
}

func (x *ListPodsResponse) GetPods() []*PodKey {
	if x != nil {
		return x.Pods
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_hub_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{12}
}

type HealthCheckResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Healthy        bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	TotalSnapshots int64                  `protobuf:"varint,3,opt,name=total_snapshots,json=totalSnapshots,proto3" json:"total_snapshots,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_hub_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_hub_proto_rawDescGZIP(), []int{13}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetTotalSnapshots() int64 {
	if x != nil {
		return x.TotalSnapshots
	}
	return 0
}

var File_hub_proto protoreflect.FileDescriptor

const file_hub_proto_rawDesc = "" +
	"\n" +
	"\thub.proto\x12\x0einsight.hub.v1\"\xde\x02\n" +
	"\x10ResourceSnapshot\x12*\n" +
	"\x11timestamp_unix_ms\x18\x01 \x01(\x03R\x0ftimestampUnixMs\x12'\n" +
	"\x0fcpu_utilization\x18\x02 \x01(\x01R\x0ecpuUtilization\x12-\n" +
	"\x12memory_utilization\x18\x03 \x01(\x01R\x11memoryUtilization\x12'\n" +
	"\x0fgpu_utilization\x18\x04 \x01(\x01R\x0egpuUtilization\x124\n" +
	"\x16storage_io_utilization\x18\x05 \x01(\x01R\x14storageIoUtilization\x12(\n" +
	"\rpod_namespace\x18\x06 \x01(\tH\x00R\fpodNamespace\x88\x01\x01\x12\x1e\n" +
	"\bpod_name\x18\a \x01(\tH\x01R\apodName\x88\x01\x01B\x10\n" +
	"\x0e_pod_namespaceB\v\n" +
	"\t_pod_name\"s\n" +
	"\x14SubmitHistoryRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12>\n" +
	"\tsnapshots\x18\x02 \x03(\v2 .insight.hub.v1.ResourceSnapshotR\tsnapshots\"d\n" +
	"\x15SubmitHistoryResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12/\n" +
	"\x13snapshots_processed\x18\x02 \x01(\x05R\x12snapshotsProcessed\"}\n" +
	"\x15GetNodeHistoryRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\"\n" +
	"\rsince_unix_ms\x18\x02 \x01(\x03R\vsinceUnixMs\x12#\n" +
	"\rmax_snapshots\x18\x03 \x01(\x05R\fmaxSnapshots\"X\n" +
	"\x16GetNodeHistoryResponse\x12>\n" +
	"\tsnapshots\x18\x01 \x03(\v2 .insight.hub.v1.ResourceSnapshotR\tsnapshots\"\x12\n" +
	"\x10ListNodesRequest\"2\n" +
	"\x11ListNodesResponse\x12\x1d\n" +
	"\n" +
	"node_names\x18\x01 \x03(\tR\tnodeNames\"\xbc\x01\n" +
	"\x14GetPodHistoryRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12#\n" +
	"\rpod_namespace\x18\x02 \x01(\tR\fpodNamespace\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\x12\"\n" +
	"\rsince_unix_ms\x18\x04 \x01(\x03R\vsinceUnixMs\x12#\n" +
	"\rmax_snapshots\x18\x05 \x01(\x05R\fmaxSnapshots\"W\n" +
	"\x15GetPodHistoryResponse\x12>\n" +
	"\tsnapshots\x18\x01 \x03(\v2 .insight.hub.v1.ResourceSnapshotR\tsnapshots\"\x11\n" +
	"\x0fListPodsRequest\"e\n" +
	"\x06PodKey\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12#\n" +
	"\rpod_namespace\x18\x02 \x01(\tR\fpodNamespace\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\">\n" +
	"\x10ListPodsResponse\x12*\n" +
	"\x04pods\x18\x01 \x03(\v2\x16.insight.hub.v1.PodKeyR\x04pods\"\x14\n" +
	"\x12HealthCheckRequest\"r\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12'\n" +
	"\x0ftotal_snapshots\x18\x03 \x01(\x03R\x0etotalSnapshots2\xad\x04\n" +
	"\x11InsightHubService\x12`\n" +
	"\x11SubmitHistoryData\x12$.insight.hub.v1.SubmitHistoryRequest\x1a%.insight.hub.v1.SubmitHistoryResponse\x12_\n" +
	"\x0eGetNodeHistory\x12%.insight.hub.v1.GetNodeHistoryRequest\x1a&.insight.hub.v1.GetNodeHistoryResponse\x12\\\n" +
	"\rGetPodHistory\x12$.insight.hub.v1.GetPodHistoryRequest\x1a%.insight.hub.v1.GetPodHistoryResponse\x12P\n" +
	"\tListNodes\x12 .insight.hub.v1.ListNodesRequest\x1a!.insight.hub.v1.ListNodesResponse\x12M\n" +
	"\bListPods\x12\x1f.insight.hub.v1.ListPodsRequest\x1a .insight.hub.v1.ListPodsResponse\x12V\n" +
	"\vHealthCheck\x12\".insight.hub.v1.HealthCheckRequest\x1a#.insight.hub.v1.HealthCheckResponseB\x19Z\x17insight-hub/proto/hubpbb\x06proto3"

var (
	file_hub_proto_rawDescOnce sync.Once
	file_hub_proto_rawDescData []byte
)

func file_hub_proto_rawDescGZIP() []byte {
	file_hub_proto_rawDescOnce.Do(func() {
		file_hub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hub_proto_rawDesc), len(file_hub_proto_rawDesc)))
	})
	return file_hub_proto_rawDescData
}

var file_hub_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_hub_proto_goTypes = []any{
	(*ResourceSnapshot)(nil),       // 0: insight.hub.v1.ResourceSnapshot
	(*SubmitHistoryRequest)(nil),   // 1: insight.hub.v1.SubmitHistoryRequest
	(*SubmitHistoryResponse)(nil),  // 2: insight.hub.v1.SubmitHistoryResponse
	(*GetNodeHistoryRequest)(nil),  // 3: insight.hub.v1.GetNodeHistoryRequest
	(*GetNodeHistoryResponse)(nil), // 4: insight.hub.v1.GetNodeHistoryResponse
	(*ListNodesRequest)(nil),       // 5: insight.hub.v1.ListNodesRequest
	(*ListNodesResponse)(nil),      // 6: insight.hub.v1.ListNodesResponse
	(*GetPodHistoryRequest)(nil),   // 7: insight.hub.v1.GetPodHistoryRequest
	(*GetPodHistoryResponse)(nil),  // 8: insight.hub.v1.GetPodHistoryResponse
	(*ListPodsRequest)(nil),        // 9: insight.hub.v1.ListPodsRequest
	(*PodKey)(nil),                 // 10: insight.hub.v1.PodKey
	(*ListPodsResponse)(nil),       // 11: insight.hub.v1.ListPodsResponse
	(*HealthCheckRequest)(nil),     // 12: insight.hub.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 13: insight.hub.v1.HealthCheckResponse
}
var file_hub_proto_depIdxs = []int32{
	0,  // 0: insight.hub.v1.SubmitHistoryRequest.snapshots:type_name -> insight.hub.v1.ResourceSnapshot
	0,  // 1: insight.hub.v1.GetNodeHistoryResponse.snapshots:type_name -> insight.hub.v1.ResourceSnapshot
	0,  // 2: insight.hub.v1.GetPodHistoryResponse.snapshots:type_name -> insight.hub.v1.ResourceSnapshot
	10, // 3: insight.hub.v1.ListPodsResponse.pods:type_name -> insight.hub.v1.PodKey
	1,  // 4: insight.hub.v1.InsightHubService.SubmitHistoryData:input_type -> insight.hub.v1.SubmitHistoryRequest
	3,  // 5: insight.hub.v1.InsightHubService.GetNodeHistory:input_type -> insight.hub.v1.GetNodeHistoryRequest
	7,  // 6: insight.hub.v1.InsightHubService.GetPodHistory:input_type -> insight.hub.v1.GetPodHistoryRequest
	5,  // 7: insight.hub.v1.InsightHubService.ListNodes:input_type -> insight.hub.v1.ListNodesRequest
	9,  // 8: insight.hub.v1.InsightHubService.ListPods:input_type -> insight.hub.v1.ListPodsRequest
	12, // 9: insight.hub.v1.InsightHubService.HealthCheck:input_type -> insight.hub.v1.HealthCheckRequest
	2,  // 10: insight.hub.v1.InsightHubService.SubmitHistoryData:output_type -> insight.hub.v1.SubmitHistoryResponse
	4,  // 11: insight.hub.v1.InsightHubService.GetNodeHistory:output_type -> insight.hub.v1.GetNodeHistoryResponse
	8,  // 12: insight.hub.v1.InsightHubService.GetPodHistory:output_type -> insight.hub.v1.GetPodHistoryResponse
	6,  // 13: insight.hub.v1.InsightHubService.ListNodes:output_type -> insight.hub.v1.ListNodesResponse
	11, // 14: insight.hub.v1.InsightHubService.ListPods:output_type -> insight.hub.v1.ListPodsResponse
	13, // 15: insight.hub.v1.InsightHubService.HealthCheck:output_type -> insight.hub.v1.HealthCheckResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_hub_proto_init() }
func file_hub_proto_init() {
	if File_hub_proto != nil {
		return
	}
	file_hub_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub_proto_rawDesc), len(file_hub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hub_proto_goTypes,
		DependencyIndexes: file_hub_proto_depIdxs,
		MessageInfos:      file_hub_proto_msgTypes,
	}.Build()
	File_hub_proto = out.File
	file_hub_proto_goTypes = nil
	file_hub_proto_depIdxs = nil
}
