// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.30.2
// source: hub.proto

package hubpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	InsightHubService_SubmitHistoryData_FullMethodName = "/insight.hub.v1.InsightHubService/SubmitHistoryData"
	InsightHubService_GetNodeHistory_FullMethodName    = "/insight.hub.v1.InsightHubService/GetNodeHistory"
	InsightHubService_GetPodHistory_FullMethodName     = "/insight.hub.v1.InsightHubService/GetPodHistory"
	InsightHubService_ListNodes_FullMethodName         = "/insight.hub.v1.InsightHubService/ListNodes"
	InsightHubService_ListPods_FullMethodName          = "/insight.hub.v1.InsightHubService/ListPods"
	InsightHubService_HealthCheck_FullMethodName       = "/insight.hub.v1.InsightHubService/HealthCheck"
)

// InsightHubServiceClient is the client API for InsightHubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InsightHubServiceClient interface {
	SubmitHistoryData(ctx context.Context, in *SubmitHistoryRequest, opts ...grpc.CallOption) (*SubmitHistoryResponse, error)
	GetNodeHistory(ctx context.Context, in *GetNodeHistoryRequest, opts ...grpc.CallOption) (*GetNodeHistoryResponse, error)
	// Pod 단위 스냅샷(워크로드 구분). node_name + pod_namespace + pod_name 로 식별.
	GetPodHistory(ctx context.Context, in *GetPodHistoryRequest, opts ...grpc.CallOption) (*GetPodHistoryResponse, error)
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	// Pod 키(ns/name)가 있는 행만 나열 (노드 집계와 분리)
	ListPods(ctx context.Context, in *ListPodsRequest, opts ...grpc.CallOption) (*ListPodsResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type insightHubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInsightHubServiceClient(cc grpc.ClientConnInterface) InsightHubServiceClient {
	return &insightHubServiceClient{cc}
}

func (c *insightHubServiceClient) SubmitHistoryData(ctx context.Context, in *SubmitHistoryRequest, opts ...grpc.CallOption) (*SubmitHistoryResponse, error) {
	out := new(SubmitHistoryResponse)
	err := c.cc.Invoke(ctx, InsightHubService_SubmitHistoryData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightHubServiceClient) GetNodeHistory(ctx context.Context, in *GetNodeHistoryRequest, opts ...grpc.CallOption) (*GetNodeHistoryResponse, error) {
	out := new(GetNodeHistoryResponse)
	err := c.cc.Invoke(ctx, InsightHubService_GetNodeHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightHubServiceClient) GetPodHistory(ctx context.Context, in *GetPodHistoryRequest, opts ...grpc.CallOption) (*GetPodHistoryResponse, error) {
	out := new(GetPodHistoryResponse)
	err := c.cc.Invoke(ctx, InsightHubService_GetPodHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightHubServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, InsightHubService_ListNodes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightHubServiceClient) ListPods(ctx context.Context, in *ListPodsRequest, opts ...grpc.CallOption) (*ListPodsResponse, error) {
	out := new(ListPodsResponse)
	err := c.cc.Invoke(ctx, InsightHubService_ListPods_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightHubServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, InsightHubService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InsightHubServiceServer is the server API for InsightHubService service.
// All implementations must embed UnimplementedInsightHubServiceServer
// for forward compatibility
type InsightHubServiceServer interface {
	SubmitHistoryData(context.Context, *SubmitHistoryRequest) (*SubmitHistoryResponse, error)
	GetNodeHistory(context.Context, *GetNodeHistoryRequest) (*GetNodeHistoryResponse, error)
	// Pod 단위 스냅샷(워크로드 구분). node_name + pod_namespace + pod_name 로 식별.
	GetPodHistory(context.Context, *GetPodHistoryRequest) (*GetPodHistoryResponse, error)
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	// Pod 키(ns/name)가 있는 행만 나열 (노드 집계와 분리)
	ListPods(context.Context, *ListPodsRequest) (*ListPodsResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedInsightHubServiceServer()
}

// UnimplementedInsightHubServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInsightHubServiceServer struct {
}

func (UnimplementedInsightHubServiceServer) SubmitHistoryData(context.Context, *SubmitHistoryRequest) (*SubmitHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitHistoryData not implemented")
}
func (UnimplementedInsightHubServiceServer) GetNodeHistory(context.Context, *GetNodeHistoryRequest) (*GetNodeHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeHistory not implemented")
}
func (UnimplementedInsightHubServiceServer) GetPodHistory(context.Context, *GetPodHistoryRequest) (*GetPodHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPodHistory not implemented")
}
func (UnimplementedInsightHubServiceServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedInsightHubServiceServer) ListPods(context.Context, *ListPodsRequest) (*ListPodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPods not implemented")
}
func (UnimplementedInsightHubServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedInsightHubServiceServer) mustEmbedUnimplementedInsightHubServiceServer() {}

// UnsafeInsightHubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InsightHubServiceServer will
// result in compilation errors.
type UnsafeInsightHubServiceServer interface {
	mustEmbedUnimplementedInsightHubServiceServer()
}

func RegisterInsightHubServiceServer(s grpc.ServiceRegistrar, srv InsightHubServiceServer) {
	s.RegisterService(&InsightHubService_ServiceDesc, srv)
}

func _InsightHubService_SubmitHistoryData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightHubServiceServer).SubmitHistoryData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightHubService_SubmitHistoryData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightHubServiceServer).SubmitHistoryData(ctx, req.(*SubmitHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightHubService_GetNodeHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightHubServiceServer).GetNodeHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightHubService_GetNodeHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightHubServiceServer).GetNodeHistory(ctx, req.(*GetNodeHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightHubService_GetPodHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightHubServiceServer).GetPodHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightHubService_GetPodHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightHubServiceServer).GetPodHistory(ctx, req.(*GetPodHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightHubService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightHubServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightHubService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightHubServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightHubService_ListPods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightHubServiceServer).ListPods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightHubService_ListPods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightHubServiceServer).ListPods(ctx, req.(*ListPodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightHubService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightHubServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightHubService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightHubServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InsightHubService_ServiceDesc is the grpc.ServiceDesc for InsightHubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InsightHubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "insight.hub.v1.InsightHubService",
	HandlerType: (*InsightHubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitHistoryData",
			Handler:    _InsightHubService_SubmitHistoryData_Handler,
		},
		{
			MethodName: "GetNodeHistory",
			Handler:    _InsightHubService_GetNodeHistory_Handler,
		},
		{
			MethodName: "GetPodHistory",
			Handler:    _InsightHubService_GetPodHistory_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _InsightHubService_ListNodes_Handler,
		},
		{
			MethodName: "ListPods",
			Handler:    _InsightHubService_ListPods_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _InsightHubService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hub.proto",
}
