apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - daemonset.yaml
images:
  - name: ai-storage-metric-collector
    newName: ketidevit2/ai-storage-metric-collector
    newTag: "f4178f3"
