# This rule is not used by the project orchestration-policy-engine itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the apollo.keti.re.kr.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: orchestration-policy-engine
    app.kubernetes.io/managed-by: kustomize
  name: orchestrationpolicy-editor-role
rules:
- apiGroups:
  - apollo.keti.re.kr
  resources:
  - orchestrationpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apollo.keti.re.kr
  resources:
  - orchestrationpolicies/status
  verbs:
  - get
