# This rule is not used by the project orchestration-policy-engine itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to apollo.keti.re.kr resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: orchestration-policy-engine
    app.kubernetes.io/managed-by: kustomize
  name: orchestrationpolicy-viewer-role
rules:
- apiGroups:
  - apollo.keti.re.kr
  resources:
  - orchestrationpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apollo.keti.re.kr
  resources:
  - orchestrationpolicies/status
  verbs:
  - get
