apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-storage-workloads
resources:
  - pvc.yaml
  - job.yaml
images:
  - name: training-job
    newName: ketidevit2/training-job-cpu
    newTag: "e5853d5"
