apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-job-data
  namespace: ai-storage-workloads
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: storage-l2
  resources:
    requests:
      storage: 1Gi
